# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: 'yarn'

      - name: yarn install
        run: yarn install
      - name: Lint check
        run: yarn lint
      - name: Typescript check
        run: yarn tslint

      - name: Cypress run
        uses: cypress-io/github-action@v4
        timeout-minutes: 30
        with:
          build: yarn build
          start: yarn start
